Repository sethverrill/rancid-tomatillos, pull requests merged in 2024-12, with the labels that each got.

#30 Set up app with structure and Title layout working
  src/App/App.js
Labels: Iteration 1

#31 Movie tiles
  src/App/App.js
  src/MoviesContainer/MoviesContainer.js
  src/index.css
Labels: enhancement, Iteration 1

#32 Voting
  src/App/App.js
  src/MoviesContainer/MoviesContainer.css
  src/MoviesContainer/MoviesContainer.js
  src/index.css
Labels: Iteration 2

#39 bug fix: reset movie details to null before each new fetch
  src/App/App.js
Labels: enhancement

#40 Cypress
  cypress/e2e/main.cy.js
  cypress/e2e/movie_container_spec.cy.js
  cypress/e2e/movie_details_spec.cy.js
  package-lock.json
  package.json
Labels: enhancement

#43 Cypress dash
  cypress/e2e/dashboard_spec.cy.js
  cypress/e2e/movie_container_spec.cy.js
Labels: enhancement, Iteration 5

#44 test: Cypress test for Movie Details page
  cypress/e2e/movie_details_spec.cy.js
  cypress/fixtures/movie_details.json
  cypress/fixtures/parasite_details.json
Labels: enhancement, Iteration 5

#45 Router refactor
  cypress/e2e/dashboard_spec.cy.js
  cypress/e2e/movie_details_spec.cy.js
  package-lock.json
  package.json
  src/App/App.js
  src/MovieDetails/MovieDetails.js
  src/MoviesContainer/MoviesContainer.js
  src/index.js
Labels: enhancement, Iteration 6

#47 Timeout patch
  public/_redirects
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
Labels: enhancement, Iteration 6

#48 Readme
  README.md
  architecture.png
Labels: documentation

#49 Live search
  src/App/App.js
  src/MoviesContainer/MoviesContainer.js
Labels: enhancement, Extensions

#51 added testing to validate functionality of serach bar
  cypress/e2e/search_spec.cy.js
  src/App/App.css
  src/App/App.js
  src/MovieDetails/MovieDetails.css
Labels: enhancement, Extensions
